### PR TITLE
fixed topic name in README.md for motor_speed

### PR DESCRIPTION
**Pull request by ffurrer**

### CODE REVIEW

**Comment by markusachtelik** [comment]
lgtm. I just think that I saw this in some other places, too. Best use the constants in here: https://github.com/ethz-asl/mav_comm/blob/master/mav_msgs/include/mav_msgs/default_topics.h

**Comment by ffurrer** [comment]
this is just a command line call, so as far as I know there is no easy way to use the constants

**Comment by ffurrer** [comment]
@markusachtelik @simonlynen did you already try to fix the issue with pcl?

**Comment by ffurrer** [comment]
test this please

**Comment by ffurrer** [comment]
test this please

**Comment by ffurrer** [comment]
test this please

**Comment by burrimi** [comment]
lgtm.

**Pull request merged**
