### PR TITLE
added IMU struct

### PR DESCRIPTION
**Pull request by mikeallenspach**
I will apply the changes directly to master, according to: https://github.com/ethz-asl/rotors_simulator/pull/574#issuecomment-503102174

### CODE REVIEW

**Comment by Jaeyoung-Lim** [comment]
test this please

**Comment by michaelpantic** [comment]
I'm not sure this is still needed.
@mikeallenspach  what do you think?

**Comment by mikeallenspach** [comment]
Agreed, we can probably remove this.
I believe it is still related to the now deprecated control repository.

**Comment by Jaeyoung-Lim** [comment]
@mikeallenspach Thanks for the clarification! Closing

**Pull request closed without merging**
