### PR TITLE
Fix/neo11 namespace

### PR DESCRIPTION
**Pull request by andretag**
Uniform argument naming with firefly.xacro and ease spawning of multiple helicopters.

### CODE REVIEW

**Comment by fmina** [comment]
LGTM

**Comment by helenol** [comment]
add to whitelist

**Comment by helenol** [comment]
Obviously no risk from this PR, but in general let's try to make sure Jenkins tests stuff before we merge ;)

**Comment by andretag** [comment]
ok @helenol, sorry for the trouble

**Pull request merged**
