### PR TITLE
Crazyflie 2.0: model and control

### PR DESCRIPTION
**Pull request by gsilano**
In this branch, the [Crazyflie 2.0](https://www.bitcraze.io/crazyflie-2/) nano-quadcopter among the already available  drones in RotorS has been added. The quadrotor dynamics and the high and low level control algorithm have been taken into account. In particular, the low level controller has been developed in according to the [Crazyflie firmware](https://github.com/bitcraze/crazyflie-firmware), release 2018.01.01.
The used aircraft parameters are described in https://arxiv.org/pdf/1608.05786.pdf while the sensors (both IMU and pressure) are still absent. I'm going to model them through [Kalibr](https://github.com/ethz-asl/kalibr/wiki), further commits will come soon.

### CODE REVIEW

**Comment by ffurrer** [comment]
ok to test

**Comment by ffurrer** [comment]
can you make LinearMath a dependency instead of pulling it in or use Kindr if possible

**Comment by gsilano** [comment]
I'm working to make LinearMath as a dependecy. In order to avoid not working commits, I'm testing my code with TravisCI and ros-travis-integration repository. I hope to fix it, adding further functionalities, as soon as possible.

**Comment by gsilano** [comment]
The Crazyflie IMU (MPU-9250) and the complementary filter have been added in the loop. The filter is used as [default state estimator](https://github.com/bitcraze/crazyflie-firmware/blob/7ae809eeb5b48b5d84649c713accd2d7bf3df338/src/modules/src/estimator.c) in the Crazyflie firmware, release 2018.01.01.

The reposiroty [CrazyS](https://github.com/gsilano/CrazyS) has been created with the aim of collecting and providing a complete simulation framework able to simulate the nano-quadcopter behavior in different scenarios.

**Comment by gsilano** [comment]
The code works both Ubuntu 14.04 and 16.04, take a look at attached image. I'm working to fix the issue.
screenshot 27

**Comment by gsilano** [comment]
Before closing the pull request, the latest code release was committed. As described in the previous comments, the ROS package is available on the [CrazyS repository](https://github.com/gsilano/CrazyS). There, further details on how the Crazyflie 2.0 nano-quadcopter was modeled through RotorS simulator are reported together with reference publications.

**Pull request closed without merging**
