### PR TITLE
add serial_device parameter to the launch file

### PR DESCRIPTION
**Pull request by BuriKizilkaya**
With the new launch file it is possible to establish the communication with the pixhawk with any USB interface.

### CODE REVIEW

**Review by Jaeyoung-Lim — CHANGES_REQUESTED** [review]
This will have no effect since there is no `serial_device` defined in the `spawn_fixed_wing.launch` launchfile

**Comment by Jaeyoung-Lim** [comment]
@BuriKizilkaya I am closing this PR since it has been over a year this has been open. Please reopen if you are willing to continue this PR

Thanks!

**Comment by BuriKizilkaya** [comment]
> @BuriKizilkaya I am closing this PR since it has been over a year this has been open. Please reopen if you are willing to continue this PR
> 
> Thanks!

It was a suggestion of me.

**Comment by Jaeyoung-Lim** [comment]
@BuriKizilkaya Thanks, 

If you are still interested in continuing this PR, the `serial_device` arg should be added to https://github.com/ethz-asl/rotors_simulator/blob/7f6b5529bfc793e77275ca32d8e4970a0c755e5d/rotors_gazebo/launch/fixed_wing_hil.launch#L33 rather than the spawn_fixedwing.launch file.

**Pull request closed without merging**
