### PR TITLE
fix for motors being stuck after gazebo world reset.

### PR DESCRIPTION
**Pull request by orangelynx**
For detailed description see https://github.com/ethz-asl/rotors_simulator/issues/403

### CODE REVIEW

**Comment by hitimo** [comment]
ok to test

**Comment by orangelynx** [comment]
I want to stress that this PR is just the most straight forward fix, given that the Reset Callback of the Plugin cannot be used. Any other way to detect a reset which is more performant would obviously be preferential.

**Comment by burrimi** [comment]
I never used it but can't you use the Reset() function for this purpose?
http://osrf-distributions.s3.amazonaws.com/gazebo/api/5.0.0/classgazebo_1_1ModelPlugin.html#a8d741565f990b73c96a6156c90cfcec1

**Comment by orangelynx** [comment]
Hi Michael, no unfortunately that does not work, as I have explained here: https://github.com/ethz-asl/rotors_simulator/issues/403

Shortly: The joint reset function is called after the plugin `Reset()`, rendering changes made to the joint in the plugin's `Reset()` useless.

**Comment by burrimi** [comment]
Too bad. Could you add a comment that describes why you do it here such that others also know why when looking at the code? olgtm.

**Pull request merged**
