### PR TITLE
Velodyne Puck Model and Velocity Controller with Joy

### PR DESCRIPTION
**Pull request by ozaslan**
Hi,

I am working on simulating Velodyne Puck using your Gazebo simulation packages. I thought this might be a good additional sensor for you and others as well. Though the number of edits is a dozen, most of them mesh files, new launch files etc. Hope these look helpful.

Thanks

### CODE REVIEW

**Comment by helenol** [comment]
ok to test

**Comment by ffurrer** [comment]
test this please

**Comment by marselomeri** [comment]
Is it possible to visualize the point clouds using Rviz ?

**Comment by Jaeyoung-Lim** [comment]
Closing as stale, please reopen if this is still of interest

**Pull request closed without merging**
