### PR TITLE
Fix/multiple mavs namespace conflict

### PR DESCRIPTION
**Pull request by HitszChen**
Hi, 

- Could anyone help to review the changes. In this branch, I add a suffix to the mav_name, in order to prevent namespace conflict when applying several mavs of same type. 
- You can run 

        $ roslaunch rotors_gazebo firefly_swarm_hovering_example.launch

 to have a test

### CODE REVIEW

**Comment by markusachtelik** [comment]
@ffurrer: can you please take a look? I thought we had fixed the namespace issue already.

**Comment by markusachtelik** [comment]
ok to test.

**Comment by HitszChen** [comment]
I guess not. and i found that the parameter "mav_name" in spawn_mav.launch
is not used anywhere in the rotors_despcription/urdf files.

2015-08-17 11:26 GMT+02:00 Markus Achtelik <notifications@github.com>:

**Comment by ffurrer** [comment]
@HitszChen `ok to test.` was for jenkins... :) I'll take a look at it.

**Comment by ffurrer** [comment]
test this please

**Comment by ffurrer** [comment]
@HitszChen can you test your stuff with the additional commits?

**Comment by burrimi** [comment]
works for me, if you increase the waiting time of the waypoint publisher

**Comment by HitszChen** [comment]
ok to test

2015-08-17 17:47 GMT+02:00 Fadri Furrer <notifications@github.com>:

**Comment by HitszChen** [comment]
sometimes not works, even i increase the waiting time. I think the problem
is in the waypoint_publisher which publishes waypoint message only one
time; the lee_position_controller_node may not get the published trajectory
msg correctly. I have made a test by adding a "loop" message publish in the
waypoint_publisher node, and it works.

2015-08-17 20:29 GMT+02:00 Haoyao Chen <chenhy.hit@gmail.com>:

**Comment by helenol** [comment]
Sounds like the proper solution would be to latch the message; this means
that when a new subscriber subscribes, it gets the last message published
on the topic, and is an option in the publisher.

**Comment by ffurrer** [comment]
test this please

**Comment by ffurrer** [comment]
Latching doesn't work here as the node is exiting after publishing. Hence, we are waiting for a subscriber to the waypoint topic.

**Comment by burrimi** [comment]
thanks @ffurrer lgtm.

**Comment by HitszChen** [comment]
thanks.

2015-08-18 4:29 GMT-07:00 Fadri Furrer <notifications@github.com>:

**Pull request merged**
