### PR TITLE
DONOTMERGE (yet) Feature/gazebo9 autobackport

### PR DESCRIPTION
**Pull request by michaelpantic**
- Scripts that automatically backport Gazebo9 to gazebo7 code
- Let's see if it builds on jenkins..

### CODE REVIEW

**Comment by michaelpantic** [comment]
@ffurrer  don't need to review yet, just approve it so that it builds on jenkins

**Comment by ffurrer** [comment]
ok, seems to work again on OSX :).

Just had to export the GAZEBO_PLUGIN_PATH variable:
```bash
export GAZEBO_PLUGIN_PATH=<path_to_catkin_ws>/devel/lib/:/usr/local/Cellar/gazebo9/9.5.0/lib/gazebo-9/plugins:/opt/ros/melodic/lib/
```

**Comment by michaelpantic** [comment]
test this please

**Comment by michaelpantic** [comment]
test this please

**Comment by michaelpantic** [comment]
@ffurrer 
As of today, tested and works on the following configurations:
Ubuntu 16.04 / Kinetic / Gazebo 7 (our buildfarm)
Ubuntu 14.04 / Indigo / Gazebo very old (our buildfarm)
Mac OS / Indigo / ?? (our buildfarm)
Docker Pre-release for ros.org on Indigo/Kinetic/Melodic
Docker w Ubuntu 14.04 / Indigo / ROS buildfarm
Ubuntu 18.04 / Melodic / Gazebo 9  (Michael)
Mac OS / ?? / Gazebo 9.5 ( Fadri)
Mac OS / Kinetic / Gazebo 7 ( Helen)
Ubuntu 16.04 / Kinetic / Gazebo 7 ( Max)


Next steps:
- Create melodic track for rosbuild farm (should be tested by next week)
- If that works too, we bump version to 3.1.0 (because for some reason there is a 3.0.0 package released somewhere...), 
- merge this into master 
- and do bloom-releses/pull requests on rosdistro for indigo/kinetic/melodic

**Comment by ffurrer** [comment]
That sounds great to me :). We should probably remove the devel release again afterwards or what do you think?

**Comment by michaelpantic** [comment]
@ffurrer  will do that before releasing probably next week - thanks, good catch.

**Comment by michaelpantic** [comment]
@ffurrer I think this is now tested enough. Will merge to master.

**Comment by ffurrer** [comment]
sweet, go ahead :)

**Pull request merged**
