### PR TITLE
Autodetect mavlink for building mavlink_interface_plugin

### PR DESCRIPTION
**Pull request by kajabo**
Add if statement that searched for mavlink package, builds plugin if found.

### CODE REVIEW

**Comment by ffurrer** [comment]
test this please

**Comment by michaelpantic** [comment]
test this please

**Comment by michaelpantic** [comment]
Clsoing this, as I already included it into our gazebo9-autobackport version and tested on many build configs (which will soon be merged into master)

**Comment by ffurrer** [comment]
can we also delete the branch?

**Pull request closed without merging**
