### PR TITLE
[DO NOT MERGE] feature/px4_merge_2

### PR DESCRIPTION
**Pull request by gbmhunter**
(cherry picked from commit 4e7b5f492afa774032b589d840a673c472268dba)

### CODE REVIEW

**Comment by ffurrer** [comment]
@gbmhunter do we really need to copy all these mavlink files? Can we not include them differently?

**Comment by gbmhunter** [comment]
@ffurrer They are from https://github.com/mavlink/c_library_v1. I looked for other source, and I have noted they are installed with ROS indigo (`/opt/ros/indigo/include/mavlink/v1.0/`).

The problem is, how would these be made available when ROS is not present? If they were a catkin package, they could be included as such. I could add them as a git submodule to the rotors_simulator repo, if you think that is any better?

Another way would be a script that grabbed them, but I think that wouldn't be worth the added complexity.

**Comment by gbmhunter** [comment]
@ffurrer what if in the case where catkin is present it automatically looks for the headers under the ROS install, otherwise it expects the header include directory to be passed into the CMake script as a parameter?

**Comment by ffurrer** [comment]
@gbmhunter can you try to keep the original structure of the different models in `rotors_description` and only have one `multirotor_base.xacro` and `component_snippets.xacro` file. It's fine to keep the models which have 'no intelligence` in `rotors_gazebo`, but try to have the actual multirotor models in `rotors_description`.

**Comment by gbmhunter** [comment]
@ffurrer Yes the two `component_snippets.xacro` and `multirotor_base.xacro` files are not nice. I tried to merge them, but had difficulties due to PX4 not using the full ROS xacro package.

For now it would be preferred to leave as to get the code merged with `master` ASAP, and possibly fix this at a later date (potentially by getting PX4 to use the full xacro module as you suggested via email).

**Comment by ffurrer** [comment]
@gbmhunter ok, yes, then open an issue for this and we keep it this 'not nice' way for now.

**Comment by gbmhunter** [comment]
@ffurrer thanks, I have opened an issue at https://github.com/ethz-asl/rotors_simulator/issues/348 .

Can this be merged?

**Pull request merged**
