### PR TITLE
Fix/replaced geodetic utils with gps common

### LINKED ISSUE #410: [ROS buildfarm] Replace geodetic_utils with libgpsd

### PR DESCRIPTION
**Pull request by hitimo**
fixed #410

### CODE REVIEW

**Comment by fmina** [comment]
Shouldn't we merge master in `fix/gps_noise_and_conversion` first?

**Comment by hitimo** [comment]
That's what I did?

**Comment by hitimo** [comment]
test this please

**Comment by fmina** [comment]
I installed `gps_common` on Jenkins node, but it fails because you are missing `find_package(gps_common)` line in the cmakelists.

**Comment by hitimo** [comment]
Still failed on the-mac-mini: (job 696)

**Comment by fmina** [comment]
I fixed the include problem, you also need to add `include_directories(${gps_common_INCLUDE_DIRS})` but the issue is more complex...

On OSX there is no libgps library, and if you clone `gps_umd` repo `gpsd_client` will fail. However this is not needed at all by rotors.

Since you only need the conversions, I suggest that we create a copy of the conversions header https://github.com/swri-robotics/gps_umd/blob/master/gps_common/include/gps_common/conversions.h in `rotors_gazebo_plugins` and remove all dependencies on `gps_common`.

**Comment by hitimo** [comment]
Ok, sure. Thanks for looking into the osx issue.

**Comment by ffurrer** [comment]
@hitimo @fmina, should this be closed?

**Comment by michaelpantic** [comment]
PR years old - closing

**Pull request closed without merging**
