### PR TITLE
FIX publish msg and not msg pointer in waypoint_publisher

### LINKED ISSUE #373: Problem with mav_with_waypoint_publisher.launch example
i want to use waypoint_publisher to plan a path for mav.
BUT when i  tried to launch the mav_with_waypoint_publisher.launch , everything was fine except the waypoint_publisher_file, which was automatically  cleaned.WHY and how to solve it?

here is the summary.

SUMMARY
========

PARAMETERS
 * /firefly/lee_position_controller_node/angular_rate_gain/x: 0.52
 * /firefly/lee_position_controller_node/angular_rate_gain/y: 0.52
 * /firefly/lee_position_controller_node/angular_rate_gain/z: 0.18
 * /firefly/lee_position_controller_node/attitude_gain/x: 3
 * /firefly/lee_position_controller_node/attitude_gain/y: 3
 * /firefly/lee_position_controller_node/attitude_gain/z: 0.15
 * /firefly/lee_position_controller_node/inertia/xx: 0.0347563
 * /firefly/lee_position_controller_node/inertia/xy: 0.0
 * /firefly/lee_position_controller_node/inertia/xz: 0.0
 * /firefly/lee_position_controller_node/inertia/yy: 0.0458929
 * /firefly/lee_position_controller_node/inertia/yz: 0.0
 * /firefly/lee_position_controller_node/inertia/zz: 0.0977
 * /firefly/lee_position_controller_node/mass: 1.56779
 * /firefly/lee_position_controller_node/position_gain/x: 6
 * /firefly/lee_position_controller_node/position_gain/y: 6
 * /firefly/lee_position_controller_node/position_gain/z: 6
 * /firefly/lee_position_controller_node/rotor_configuration/0/angle: 0.52359877559
 * /firefly/lee_position_controller_node/rotor_configuration/0/arm_length: 0.215
 * /firefly/lee_position_controller_node/rotor_configuration/0/direction: 1.0
 * /firefly/lee_position_controller_node/rotor_configuration/0/rotor_force_constant: 8.54858e-06
 * /firefly/lee_position_controller_node/rotor_configuration/0/rotor_moment_constant: 0.016
 * /firefly/lee_position_controller_node/rotor_configuration/1/angle: 1.57079632679
 * /firefly/lee_position_controller_node/rotor_configuration/1/arm_length: 0.215
 * /firefly/lee_position_controller_node/rotor_configuration/1/direction: -1.0
 * /firefly/lee_position_controller_node/rotor_configuration/1/rotor_force_constant: 8.54858e-06
 * /firefly/lee_position_controller_node/rotor_configuration/1/rotor_moment_constant: 0.016
 * /firefly/lee_position_controller_node/rotor_configuration/2/angle: 2.61799387799
 * /firefly/lee_position_controller_node/rotor_configuration/2/arm_length: 0.215
 * /firefly/lee_position_controller_node/rotor_configuration/2/direction: 1.0
 * /firefly/lee_position_controller_node/rotor_configuration/2/rotor_force_constant: 8.54858e-06
 * /firefly/lee_position_controller_node/rotor_configuration/2/rotor_moment_constant: 0.016
 * /firefly/lee_position_controller_node/rotor_configuration/3/angle: -2.61799387799
 * /firefly/lee_position_controller_node/rotor_configuration/3/arm_length: 0.215
 * /firefly/lee_position_controller_node/rotor_configuration/3/direction: -1.0
 * /firefly/lee_position_controller_node/rotor_configuration/3/rotor_force_constant: 8.54858e-06
 * /firefly/lee_position_controller_node/rotor_configuration/3/rotor_moment_constant: 0.016
 * /firefly/lee_position_controller_node/rotor_configuration/4/angle: -1.57079632679
 * /firefly/lee_position_controller_node/rotor_configuration/4/arm_length: 0.215
 * /firefly/lee_position_controller_node/rotor_configuration/4/direction: 1.0
 * /firefly/lee_position_controller_node/rotor_configuration/4/rotor_force_constant: 8.54858e-06
 * /firefly/lee_position_controller_node/rotor_configuration/4/rotor_moment_constant: 0.016
 * /firefly/lee_position_controller_node/rotor_configuration/5/angle: -0.52359877559
 * /firefly/lee_position_controller_node/rotor_configuration/5/arm_length: 0.215
 * /firefly/lee_position_controller_node/rotor_configuration/5/direction: -1.0
 * /firefly/lee_position_controller_node/rotor_configuration/5/rotor_force_constant: 8.54858e-06
 * /firefly/lee_position_controller_node/rotor_configuration/5/rotor_moment_constant: 0.016
 * /firefly/lee_position_controller_node/velocity_gain/x: 4.7
 * /firefly/lee_position_controller_node/velocity_gain/y: 4.7
 * /firefly/lee_position_controller_node/velocity_gain/z: 4.7
 * /firefly/robot_description: <?xml version="1....
 * /firefly/tf_prefix: 
 * /rosdistro: kinetic
 * /rosversion: 1.12.6
 * /use_sim_time: True

NODES
  /firefly/
    hovering_example (rotors_gazebo/hovering_example)
    joint_state_publisher (joint_state_publisher/joint_state_publisher)
    lee_position_controller_node (rotors_control/lee_position_controller_node)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    spawn_firefly (gazebo_ros/spawn_model)
    waypoint_publisher_file (rotors_gazebo/waypoint_publisher_file)
  /
    gazebo (gazebo_ros/gzserver)
    gazebo_gui (gazebo_ros/gzclient)

auto-starting new master
process[master]: started with pid [9960]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to f9e089a4-0eaf-11e7-a5ad-e839dfdbba03
process[rosout-1]: started with pid [9973]
started core service [/rosout]
process[gazebo-2]: started with pid [9997]
process[gazebo_gui-3]: started with pid [10002]
process[firefly/spawn_firefly-4]: started with pid [10007]
process[firefly/lee_position_controller_node-5]: started with pid [10008]
process[firefly/hovering_example-6]: started with pid [10011]
process[firefly/waypoint_publisher_file-7]: started with pid [10039]
[ INFO] [1490153466.601706907]: Started hovering example.
[ INFO] [1490153466.605113502]: Wait for 1 second before trying to unpause Gazebo again.
process[firefly/robot_state_publisher-8]: started with pid [10052]
process[firefly/joint_state_publisher-9]: started with pid [10058]
[ INFO] [1490153466.716463539]: Started waypoint_publisher.
[ INFO] [1490153466.716711746]: Read 4 waypoints.
[ INFO] [1490153466.775819158]: Wait for simulation to become ready...
SpawnModel script started
[INFO] [1490153467.228502, 0.000000]: Loading model XML from ros parameter
[INFO] [1490153467.235381, 0.000000]: Waiting for service /gazebo/spawn_urdf_model
[ INFO] [1490153467.497426884]: Finished loading Gazebo ROS API Plugin.
[ INFO] [1490153467.499148606]: waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
[ INFO] [1490153467.606604383]: Wait for 1 second before trying to unpause Gazebo again.
[INFO] [1490153468.445487, 0.000000]: Calling service /gazebo/spawn_urdf_model
[INFO] [1490153468.928784, 0.000000]: Spawn status: SpawnModel: Successfully spawned model
[ INFO] [1490153468.953360285]: Unpaused the Gazebo simulation.
[firefly/spawn_firefly-4] process has finished cleanly
log file: /home/adam/.ros/log/f9e089a4-0eaf-11e7-a5ad-e839dfdbba03/firefly-spawn_firefly-4*.log
[ INFO] [1490153469.225005508, 0.030000000]: waitForService: Service [/gazebo/set_physics_properties] is now available.
[ INFO] [1490153469.326907172, 0.130000000]: Physics dynamic reconfigure ready.
[ INFO] [1490153469.502064645, 0.310000000]: ...ok
[ INFO] [1490153474.229114024, 5.010000000]: Publishing waypoint on namespace //firefly: [0.000000, 0.000000, 1.000000].
[ INFO] [1490153499.550396504, 30.310000000]: Start publishing waypoints.
**[firefly/waypoint_publisher_file-7] process has finished cleanly
log file: /home/adam/.ros/log/f9e089a4-0eaf-11e7-a5ad-e839dfdbba03/firefly-waypoint_publisher_file-7*.log**

many thanks

### PR DESCRIPTION
**Pull request by timethy**
Waypoint_publisher didn't work for me, so I dug into it.

Seems like the problem was that the pointer to the message was published instead of the message itself.
 
This would fix #373 I think.

### CODE REVIEW

**Comment by hitimo** [comment]
add to whitelist

**Comment by helenol** [comment]
This is not a correct fix.
http://docs.ros.org/jade/api/roscpp/html/classros_1_1Publisher.html#a66dbf9c51465cb3d47005f0bf312ff05 shows the publish function we are calling: it is totally fine to publish a shared pointer.

Can you give us more information about what version of ROS and gazebo your are using that causes this problem?

**Comment by timethy** [comment]
Yes, sorry, I was a little too fast.
(However, it seemed to have fixed the problem)

My gazebo version is 5.4.0, rosversion roscpp gives me 1.11.21.

I tried to launch it again (multiple times) with a standard MAV (on origin/master ae825e1):
> roslaunch rotors_gazebo mav_with_waypoint_publisher.launch
> rostopic echo /firefly/command/trajectory

Everything starts up fine, and after roughly 40seconds I get:
...
[firefly/waypoint_publisher_file-6] process has finished cleanly

However, only the first waypoint is logged (in the rostopic echo console) and the MAV does not move.

Now I only changed the waiting time from 30s to 10s (line waypoint_publisher_file.cpp:108), and it works sometimes, and sometimes not..

Maybe you can try on your system?
Thanks for looking into this

**Comment by timethy** [comment]
Update: So when I add a ros::shutdown() node before return 0; it seems to work..
Maybe the node exists faster than the message is enqueued?

**Comment by helenol** [comment]
Oh lol. Yeah that's better. And anyway stick a ros::spinOnce() before the shutdown, should have at least one after publishing. That's definitely the issue.

Cheers, thanks for finding a better fix.

**Comment by timethy** [comment]
Ok good, so would you mind approving the pull request? :)

**Pull request merged**
