### PR TITLE
pointCloudCutoffMax tag added for depth cam

### PR DESCRIPTION
**Pull request by birchera**

### CODE REVIEW

**Comment by ffurrer** [comment]
thanks, could you make it a param? `far` and `pointCloudCutoffMax` should probably also be the same.

**Comment by birchera** [comment]
should the depth camera and the visual cameras have the same range or is it necessary to allow the choice of different values?

**Comment by ffurrer** [comment]
@burrimi your opinion?

**Comment by burrimi** [comment]
I think its ok to have the same parameter for the depth camera and the visual cameras, just not sure about 15m as default parameter. Seems a bit too far.

**Comment by birchera** [comment]
Parameters can now be set on the level of the vi_sensor_macro for the visual and the depth cameras. The value for the depth cam range is now 10, while the visual cameras stay at 30

**Comment by ffurrer** [comment]
lgtm @simonlynen can you verify?

**Comment by simonlynen** [comment]
ok to test

**Comment by ffurrer** [comment]
@simonlynen thanks :)

**Pull request merged**
